### ISSUE TITLE
Support for vCenter 6.5 schema

### ISSUE THREAD

**Issue by avpk10** [bhoriuchi/vsphere-connect#10]
It would be great if you can upgrade the package.json to use latest git version of vsphere-schema., which includes 6.5 support

**Comment by bhoriuchi** [comment]
i updated v1 to use the newer version of vsphere-schema (and published a new version of vsphere-schema). v2 uses its own definitions. Let me know if v1 is working for you and ill publish a release

**Comment by avpk10** [comment]
@bhoriuchi Works perfectly fine.. please go ahead and publish a release for both repos

Once again, huge thanks for your commitment !

**Comment by avpk10** [comment]
The v1.0.1  for schema works perfect. Can you push a release for vsphere-connect v1.1.2 ?

**Comment by bhoriuchi** [comment]
published 1.1.2
