### ISSUE TITLE
nsp alerts for version 1.1.2

### ISSUE THREAD

**Issue by LA-Jobe** [bhoriuchi/vsphere-connect#14]
Branden,

The current release of has two nsp alerts for soap@0.13.0, but the master branch looks like it has updated these along with a bunch of other fixes.

Are you planning on creating a new release that includes the updates in master and updates this reference to soap?

**Comment by bhoriuchi** [comment]
the master branch is a newer version of the package (2.x) that has a different api and uses custom code for soap. I published an alpha release a while ago that you can use `2.0.0-alpha.0` the api is documented here http://bhoriuchi.github.io/vsphere-connect/#/api

**Comment by LA-Jobe** [comment]
Thanks Branden, will give it a try and follow up...

**Comment by LA-Jobe** [comment]
Thanks Branden, 2.0.0-alpha.0 worked, look forward to using.
