### ISSUE TITLE
Would you like to support multiple online accounts and make request through session?

### ISSUE THREAD

**Issue by lakca** [bhoriuchi/vsphere-connect#2]
In another word, inject session(token) to accessable request method instead of attaching session to client instance.

**Comment by bhoriuchi** [comment]
I'm not sure what you mean. Currently the api requires you to log in with credentials in order to obtain a session key that you can then use to make requests. If you want to support multiple accounts in your project you would just create a new client instance for each account.

**Comment by bhoriuchi** [comment]
@lakca I am casually writing a new version of this lib that will have a reql like interface. One of the chained methods that will be included will be 'token' which will allow you to pass the uuid part of a cookie and set the soap header to use that in the cookie for authentication. This will allow you to execute requests as any logged in user you have the cookie for which should mostly meet your use case

**Comment by bhoriuchi** [comment]
the current release allows you to create multiple instances of the client with different credentials, as well as call login to change credentials
