### ISSUE TITLE
is this project still active?

### ISSUE THREAD

**Issue by surfjedi** [bhoriuchi/vsphere-connect#3]
How active is this project and would you take some PR's?

**Comment by bhoriuchi** [comment]
It's more of a spare time project, however I did start a branch to modernize some of the code. My main concern is with the soap library. The WSDL cache is creates is cyclical and very large so it's hard to cache it locally like the VMware JavaScript SDK does. I started working on my own soap lib but soap has a pretty steep learning curve. I would take some PRa but it would probably be best after I merge the branch I'm working on in as there may be some large changes

**Comment by bhoriuchi** [comment]
@surfjedi to update you, I have made some progress on my soap client and am starting to integrate it into the project under the chain branch. The updated lib will have a ReQL-like API as well as access to the base client (which will have an API similar to the current API)

**Comment by bhoriuchi** [comment]
the outline of the project going forward is in the current master and development branches. PRs welcome. When i get a chance i will add a CONTRIBUTING.md
